# Generated by Django 6.0.2 on 2026-02-10 19:29

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('resume_url', models.URLField(blank=True, null=True)),
                ('resume_file', models.FileField(upload_to='resume_files/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('beworben', 'Beworben'), ('geprueft', 'Geprüft'), ('vorstellungsgespräch', 'Vorstellungsgespräch'), ('eingestellt', 'Eingestellt'), ('abgelehnt', 'Abgelehnt')], default='beworben', max_length=20)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hr_rating', models.IntegerField(blank=True, null=True)),
                ('hr_notes', models.TextField(blank=True)),
            ],
        ),
    ]
